In [2]:
import hyperspy.api as hs
import xraylib as x
import numpy as np
import os

from pathlib import Path

In [3]:
base_dir = Path(r'C:\Users\MF\LBNL_git_repos\react-explorers\backend\sample_data')

In [4]:
os.listdir(base_dir)
signal_paths = list(base_dir.glob('*.emd'))

In [5]:
for path in signal_paths:
    print(path)

C:\Users\MF\LBNL_git_repos\react-explorers\backend\sample_data\Copy of SI HAADF 1059 49000 x.emd
C:\Users\MF\LBNL_git_repos\react-explorers\backend\sample_data\Copy of SI HAADF 1119 49000 x.emd
C:\Users\MF\LBNL_git_repos\react-explorers\backend\sample_data\Copy of SI HAADF 1142 49000 x.emd
C:\Users\MF\LBNL_git_repos\react-explorers\backend\sample_data\Copy of SI HAADF 1202 49000 x.emd
C:\Users\MF\LBNL_git_repos\react-explorers\backend\sample_data\Copy_of_SI_HAADF_1038_49000_x.emd


# Hyperspy Section

## What HyperSpy Is Built For:
Handling n-dimensional data (e.g., 2D images with 1D spectra at each pixel).

Interactive visualization and analysis.

Model fitting and decomposition (e.g., PCA, ICA, NMF).

Export/import to/from common microscopy formats (e.g., .emd, .hdf5, .blo, etc.).

## Core Concept: Signal
At the heart of HyperSpy is the Signal class and its sub-classes. Think of a Signal as an enhanced NumPy array with metadata and built-in methods tailored for analysis.

### Key Signal Types:
Signal1D: For 1D spectra (e.g., EELS, EDX).

Signal2D: For 2D images.

ComplexSignal1D, ComplexSignal2D: Handle complex-valued data.

Signal3D, etc.: For higher-dimensional data.

## Useful Functions & Features:
1. Loading Data
import hyperspy.api as hs
s = hs.load("myfile.dm3")
Automatically detects the signal type and loads metadata.

2. Plotting
s.plot()
Opens an interactive GUI viewer — zoom, pan, and slice multi-dimensional data easily.

3. Slicing and Navigation
s.inav[10, 15]  # Access spectrum at pixel (10,15)
4. Data Processing


        s.decomposition() – Run PCA/ICA/NMF for dimensionality reduction.

        s.estimate_noise_variance() – Estimate noise, important for denoising or fitting.

        s.align2D() – Align images in a 2D signal.


5. Model Fitting
s.create_model()
You can create a fitting model to extract quantitative data from spectra (e.g., Gaussian peak fitting, power-law background subtraction).

6. Exporting
s.save("processed.hspy")

In [6]:
signal1 = hs.load(signal_paths[0])

In [7]:
signal1

[<EDSTEMSpectrum, title: EDS, dimensions: (|4096)>,
 <EDSTEMSpectrum, title: EDS, dimensions: (|4096)>,
 <EDSTEMSpectrum, title: EDS, dimensions: (|4096)>,
 <EDSTEMSpectrum, title: EDS, dimensions: (|4096)>,
 <Signal2D, title: Al, dimensions: (|400, 400)>,
 <Signal2D, title: Si, dimensions: (|400, 400)>,
 <Signal2D, title: Na, dimensions: (|400, 400)>,
 <Signal2D, title: K, dimensions: (|400, 400)>,
 <Signal2D, title: Ba, dimensions: (|400, 400)>,
 <Signal2D, title: HAADF, dimensions: (|400, 400)>,
 <Signal2D, title: Fe, dimensions: (|400, 400)>,
 <Signal2D, title: Rb, dimensions: (|400, 400)>,
 <Signal2D, title: O, dimensions: (|400, 400)>,
 <EDSTEMSpectrum, title: EDS, dimensions: (400, 400|4096)>]

In [8]:
type(signal1[0])

exspy.signals.eds_tem.EDSTEMSpectrum

In [9]:
type(signal1[0].data)

numpy.ndarray

In [10]:
signal1[0].data

array([0, 0, 0, ..., 0, 0, 0], shape=(4096,), dtype=uint32)

In [11]:
signal1[0].data.shape

(4096,)

In [12]:
type(signal1[0].metadata)

hyperspy.misc.utils.DictionaryTreeBrowser

In [13]:
signal1[0].metadata

├── Acquisition_instrument
│   └── TEM
│       ├── Detector
│       │   └── EDS
│       │       ├── azimuth_angle = 0.0
│       │       ├── elevation_angle = 35.0
│       │       └── energy_resolution_MnKa = 130.0
│       ├── Stage
│       │   ├── tilt_alpha = np.float64(0.0)
│       │   ├── tilt_beta = np.float64(0.0)
│       │   ├── x = -3.5e-05
│       │   ├── y = -0.000571
│       │   └── z = -8e-05
│       ├── beam_energy = 60.0
│       ├── camera_length = 196.0
│       ├── magnification = 28500.0
│       └── microscope = Titan
├── General
│   ├── FileIO
│   │   └── 0
│   │       ├── hyperspy_version = 2.3.0
│   │       ├── io_plugin = rsciio.emd
│   │       ├── operation = load
│   │       └── timestamp = 2025-07-03T12:14:31.284929-07:00
│   ├── date = 2024-10-16
│   ├── original_filename = Copy of SI HAADF 1059 49000 x.emd
│   ├── time = 10:59:27-07:00
│   ├── time_zone = Pacific Daylight Time
│   └── title = EDS
├── Sample
│   └── elements = ['O', 'Na', 'Al', 'Si', 'K', 'Fe', 'Rb', 'Ba']
└── Signal
    └── signal_type = EDS_TEM

### Axes Manager stores the information necessary to get the frequency of data stored by the EDSTEM Spectrum
frequency = offset + scale * index  
reversing:  
index = (frequency - offset) / scale

In [14]:
type(signal1[0].axes_manager)

hyperspy.axes.AxesManager

In [15]:
signal1[0].axes_manager

<Axes manager, axes: (|4096)>
            Name |   size |  index |  offset |   scale |  units 
================ | ====== | ====== | ======= | ======= | ====== 
---------------- | ------ | ------ | ------- | ------- | ------ 
          Energy |   4096 |      0 |      -1 |    0.01 |    keV

In [16]:
signal1[0].axes_manager[0].offset

-1.0

In [17]:
signal1[0].axes_manager[0].scale

0.01

In [18]:
signal1[0].axes_manager[0].units

'keV'

In [19]:
signal1[13]

<EDSTEMSpectrum, title: EDS, dimensions: (400, 400|4096)>

In [20]:
signal1[13].data

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [20]:
signal1[13].data.shape

(400, 400, 4096)

In [21]:
signal1[13].metadata

├── Acquisition_instrument
│   └── TEM
│       ├── Detector
│       │   └── EDS
│       │       ├── azimuth_angle = 0.0
│       │       ├── elevation_angle = 35.0
│       │       ├── energy_resolution_MnKa = 130.0
│       │       └── number_of_frames = 200
│       ├── Stage
│       │   ├── tilt_alpha = np.float64(0.0)
│       │   ├── tilt_beta = np.float64(0.0)
│       │   ├── x = -3.5e-05
│       │   ├── y = -0.000571
│       │   └── z = -8e-05
│       ├── beam_energy = 60.0
│       ├── camera_length = 196.0
│       ├── magnification = 28500.0
│       └── microscope = Titan
├── General
│   ├── FileIO
│   │   └── 0
│   │       ├── hyperspy_version = 2.3.0
│   │       ├── io_plugin = rsciio.emd
│   │       ├── operation = load
│   │       └── timestamp = 2025-07-03T11:20:25.600131-07:00
│   ├── date = 2024-10-16
│   ├── original_filename = Copy of SI HAADF 1059 49000 x.emd
│   ├── time = 10:59:27-07:00
│   ├── time_zone = Pacific Daylight Time
│   └── title = EDS
├── Sample
│   └── elements = ['O', 'Na', 'Al', 'Si', 'K', 'Fe', 'Rb', 'Ba']
└── Signal
    └── signal_type = EDS_TEM

## Hyperspy signal Axis Manager

In [22]:
signal1[13].axes_manager

<Axes manager, axes: (400, 400|4096)>
            Name |   size |  index |  offset |   scale |  units 
================ | ====== | ====== | ======= | ======= | ====== 
               x |    400 |      0 | -4.3e+02 |       2 |     nm 
               y |    400 |      0 | -3.9e+02 |       2 |     nm 
---------------- | ------ | ------ | ------- | ------- | ------ 
    X-ray energy |   4096 |      0 |      -1 |    0.01 |    keV

In [30]:
signal1[13].axes_manager[0]

<x axis, size: 400, index: 0>

In [31]:
signal1[13].axes_manager[0].axis

array([-430.64634578, -428.64333952, -426.64033326, -424.637327  ,
       -422.63432074, -420.63131448, -418.62830822, -416.62530196,
       -414.6222957 , -412.61928944, -410.61628318, -408.61327692,
       -406.61027066, -404.6072644 , -402.60425815, -400.60125189,
       -398.59824563, -396.59523937, -394.59223311, -392.58922685,
       -390.58622059, -388.58321433, -386.58020807, -384.57720181,
       -382.57419555, -380.57118929, -378.56818303, -376.56517677,
       -374.56217051, -372.55916425, -370.55615799, -368.55315173,
       -366.55014548, -364.54713922, -362.54413296, -360.5411267 ,
       -358.53812044, -356.53511418, -354.53210792, -352.52910166,
       -350.5260954 , -348.52308914, -346.52008288, -344.51707662,
       -342.51407036, -340.5110641 , -338.50805784, -336.50505158,
       -334.50204532, -332.49903907, -330.49603281, -328.49302655,
       -326.49002029, -324.48701403, -322.48400777, -320.48100151,
       -318.47799525, -316.47498899, -314.47198273, -312.46897

In [23]:
signal1[13].axes_manager[0].offset

-430.64634577704004

In [24]:
signal1[13].axes_manager[2].offset

-1.0

In [25]:
signal1[13].axes_manager[2].scale

0.01

In [26]:
signal1[13].axes_manager[2].units

'keV'

In [21]:
signal1[13].axes_manager[1].axis

array([-386.58020807, -384.57720181, -382.57419555, -380.57118929,
       -378.56818303, -376.56517677, -374.56217051, -372.55916425,
       -370.55615799, -368.55315173, -366.55014548, -364.54713922,
       -362.54413296, -360.5411267 , -358.53812044, -356.53511418,
       -354.53210792, -352.52910166, -350.5260954 , -348.52308914,
       -346.52008288, -344.51707662, -342.51407036, -340.5110641 ,
       -338.50805784, -336.50505158, -334.50204532, -332.49903907,
       -330.49603281, -328.49302655, -326.49002029, -324.48701403,
       -322.48400777, -320.48100151, -318.47799525, -316.47498899,
       -314.47198273, -312.46897647, -310.46597021, -308.46296395,
       -306.45995769, -304.45695143, -302.45394517, -300.45093891,
       -298.44793265, -296.4449264 , -294.44192014, -292.43891388,
       -290.43590762, -288.43290136, -286.4298951 , -284.42688884,
       -282.42388258, -280.42087632, -278.41787006, -276.4148638 ,
       -274.41185754, -272.40885128, -270.40584502, -268.40283

In [22]:
signal1[13].axes_manager[1]

<y axis, size: 400, index: 0>

In [23]:
signal1[13].axes_manager[2]

<X-ray energy axis, size: 4096>

## Using the axes_manager[2] to access the spectrum dimension, then using axis we can get the data as it is meant to be displayed in keV's

In [28]:
signal1[13].axes_manager[2].axis

array([-1.  , -0.99, -0.98, ..., 39.93, 39.94, 39.95], shape=(4096,))

In [36]:
signal1[13].isig[0.50:4]

<EDSTEMSpectrum, title: EDS, dimensions: (400, 400|0)>

In [39]:
signal1[13].isig[0.50:0.9].data

array([[[0, 0, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 3, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0]],

       [[1, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 1, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 2, ..., 0, 0, 0],
        [0, 0, 2, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 0, 1, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 2, 1, ..., 0, 0, 0]],

       ...,

       [[1, 2, 1, ..., 0, 0, 0],
        [1, 0, 1, ..., 0, 0, 0],
        [1, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 1, 1, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [1, 1, 0, ..., 0, 0, 0],
        [1, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

# xraylib section

xraylib is a C-based library with Python bindings for X-ray fluorescence, absorption, and scattering calculations. It's a highly accurate and efficient tool for people working in X-ray spectroscopy, crystallography, materials science, and related fields.

## What Is xraylib For?
You can use it to:

Get fluorescence line energies and intensities

Calculate mass attenuation coefficients

Analyze photoelectric cross-sections

Determine edge energies (K, L, M, etc.)

Simulate Rayleigh and Compton scattering

Basically, it gives you the theoretical backbone for simulating or interpreting experimental X-ray data.

## Key Features and Functions
### 1. Atomic Data
Get atomic weights, numbers, and densities:

xraylib.AtomicWeight(26)  # Iron (Fe)  

xraylib.AtomicNumber("Fe")  # 26  

xraylib.ElementDensity(26)  # g/cm³  

### 2. X-ray Line Energies
xraylib.LineEnergy(26, xraylib.KA1_LINE)  # Fe Kα1 line energy  

You can access a huge set of lines like KA1_LINE, KB1_LINE, LA1_LINE, etc.  


### 3. Cross Sections
xraylib.CS_Total(26, 10.0)  # Total cross section at 10 keV  

xraylib.CS_Photo(26, 10.0)  # Photoelectric  

xraylib.CS_Compt(26, 10.0)  # Compton scattering  

Units are typically in cm²/g.  


### 4. Edge Energies
xraylib.EdgeEnergy(26, xraylib.K_SHELL)  

Useful for interpreting spectra near absorption edges.  


### 5. Fluorescence Yields and Radiative Rates  

xraylib.FluorYield(26, xraylib.K_SHELL)  

xraylib.RadRate(26, xraylib.KA1_LINE)  

Crucial for quantifying XRF (X-ray fluorescence).  


### 6. Compound/Mixture Handling
compound = xraylib.CompoundParser("Fe2O3")  

compound["mass_fraction"][xraylib.AtomicNumber("Fe")]  # Fraction of iron  

You can also get the total cross-section for a compound:  


xraylib.CS_Total_CP("Fe2O3", 10.0)  # At 10 keV



## Why Use xraylib?
Because:

It’s fast and accurate (underlying C code).

Based on up-to-date databases like XCOM and Scofield.

It handles edge cases better than simplistic models.

Works well in scientific pipelines (e.g., with PyMCA or custom XRF analysis).

In [24]:
 Iron = x.SymbolToAtomicNumber("Fe")

In [25]:
Iron

26

In [30]:
ka1_energy = x.LineEnergy(Iron, x.KA1_LINE)
kb1_energy = x.LineEnergy(Iron, x.KB1_LINE)

In [31]:
ka1_energy

6.4039

In [32]:
kb1_energy

7.058

In [33]:
k_edge = x.EdgeEnergy(Iron, x.K_SHELL)
print(f"K-edge binding energy for Fe: {k_edge:.2f} keV")

K-edge binding energy for Fe: 7.11 keV


In [34]:
 Lithium = x.SymbolToAtomicNumber("Li")

### xraylib does not carry the ka1 line for Lithium or Beryllium, which should be 54.3 eV or 0.0543 keV. Typically these elements have extremely small emission frequencies and require specialized equipment and techniques for detecting.
### The following code will throw an error:

In [35]:
ka1_energy = x.LineEnergy(Lithium, x.KA1_LINE)

ValueError: Invalid line for this atomic number

In [41]:
Beryllium = x.SymbolToAtomicNumber("Be")
ka1_energy = x.LineEnergy(Beryllium, x.KA1_LINE)
ka1_energy

ValueError: Invalid line for this atomic number

### The first element xraylib does carry the ka1 line for is Oxygen

In [36]:
Oxygen = x.SymbolToAtomicNumber("O")
ka1_energy = x.LineEnergy(Oxygen, x.KA1_LINE)
ka1_energy

0.5249

In [44]:
Lawrencium = x.SymbolToAtomicNumber("Lr")
ka1_energy = x.LineEnergy(Lawrencium, x.KA1_LINE)
ma1_energy = x.LineEnergy(Lawrencium, x.MA1_LINE)

In [43]:
ka1_energy

130.611

In [45]:
ma1_energy

4.218

In [72]:
Carbon = x.SymbolToAtomicNumber("C")
ka1_energy = x.LineEnergy(Carbon, x.KA1_LINE)
ka1_energy

0.2774

In [73]:
Boron = x.SymbolToAtomicNumber("B")
ka1_energy = x.LineEnergy(Boron, x.KA1_LINE)
ka1_energy

0.1833